source 'https://github.com/CocoaPods/Specs.git'

target 'PXInfiniteScrollView', :exclusive => true do
  pod "PXInfiniteScrollView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXInfiniteScrollView", :path => "../"


end
