source 'https://github.com/CocoaPods/Specs.git'

target 'PXInfiniteScrollView' do
  pod "PXInfiniteScrollView", :path => "../"
end

target 'Tests' do
  pod "PXInfiniteScrollView", :path => "../"
end

target 'PXInfiniteScrollViewSwiftExample' do
    pod "PXInfiniteScrollView", :path => "../"
end

target 'PXInfiniteScrollViewSwiftExampleTests' do
    pod "PXInfiniteScrollView", :path => "../"
end
